# Generated by Django 5.0.1 on 2025-12-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='amendment',
            name='impact',
            field=models.TextField(blank=True, help_text='Constitutional impact'),
        ),
        migrations.AddField(
            model_name='amendment',
            name='long_description',
            field=models.TextField(blank=True, help_text='Full detailed explanation'),
        ),
        migrations.AddField(
            model_name='amendment',
            name='official_link',
            field=models.URLField(blank=True, help_text='Link to official Govt/PRS source'),
        ),
        migrations.AddField(
            model_name='amendment',
            name='reason',
            field=models.TextField(blank=True, help_text='Why this amendment was enacted'),
        ),
        migrations.AddField(
            model_name='judgment',
            name='source_link',
            field=models.URLField(blank=True, help_text='Link to contemporary newspaper coverage'),
        ),
        migrations.AddField(
            model_name='judgment',
            name='source_name',
            field=models.CharField(blank=True, help_text="e.g., 'The Hindu (1973)'", max_length=255),
        ),
    ]
